### ISSUE TITLE
Please add python/pip respositories to example YAML

### ISSUE THREAD

**Issue by richardj-bsquare** [sventschui/nexus-casc-plugin#2]
I'm struggling to work out a sane configuration for a python pip proxy plus repo & store just from looking at the code.

**Comment by sventschui** [comment]
Sorry for the delay, seems this Issue got lost somewhere in my GitHub notifications. 

I honestly never worked with pip repos. The best way to debug into this would be to use the nexus scripting API and try&error

**Comment by sventschui** [comment]
Closing this issue as the repo is not maintained anymore, have a look at the fork mentioned in the readme
